#!/bin/bash

if [ $# -ne 1 ]; then
  echo -e "\e[1mUsage\e[0m: audio2mp3 <audiofile-name>";
  exit 1;
fi

afile="${1#*.}"
afile="${afile^^*}"
if [ "$afile" == "MP3" ]; then
  echo -e "\e[1mError\e[0m: File '$1' is already a MP3."
  exit 1
fi

ffmpeg -y -i "$1" -vn -q:a 5 "${1%.*}.mp3" && rm "$1"
