#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: desktop-cam-capture <videoname>"
  exit 1
fi

# -framerate and -r are not the same thing for v4l2 sources.
#
# Graph:
#                                 +---------+
#  0:v -------------------------->|         |
#            +-------+            | overlay |--->[out]
#  1:v ----->| scale |--->[fg]--->|         |
#            +-------+            +---------+

ffmpeg -y -f x11grab -thread_queue_size 1024 -s hd1080 -r 30 -i :0.0 \
       -f v4l2 -pix_fmt mjpeg -thread_queue_size 1024 -s hd720 -r 15 -i /dev/video0 \
       -f alsa -thread_queue_size 1024 -ac 1 -i default \
       -filter_complex "[1:v]scale=256:-1[fg];[0:v][fg]overlay=W-w-50:H-h-30,format=yuv420p[out]" \
       -map "[out]" -map 2:a \
       -c:v libx264 -preset ultrafast -crf 19 -r 30 -maxrate 3000k -bufsize 4000k -c:a libmp3lame -b:a 64k -ar 44100 \
       "$1.mkv"
