#!/bin/bash

if [ $# -ne 1 ]; then
	echo -e "\e[1mUsage\e[0m: pic2jpg <picfile-name>";
	exit 1;
fi

gtype="${1#*.}"
gtype="${gtype^^*}"
if [ "$gtype" == "JPG" ] || [ "$gtype" == "JPEG" ]; then
  echo -e "\e[1mError\e[0m: File '$1' is a JPEG already."
  exit 1
fi

echo -e "Converting \"\e[1m$1\e[0m\" to JPEG"

convert "$1" "${1%.*}.jpg" && rm "$1"
