#!/bin/bash

#
# Need mp3gain installed.
#

if [ $# -ne 1 ]; then
  echo -e "\e[1mUsage\e[0m: vid-audio-normalize <inputvideofile>";
  exit 1;
fi

tmpaudio="$(mktemp /tmp/tmp.XXXXXXXXXX.mp3)"
tmpvideo="$(echo "$1" | sed 's/\.\([^.]*\)$/._tmp_.\1/')"
videomap="$(ffmpeg -i "$1" 2>&1 | grep "Stream" | grep "Video:" | cut -c5- | cut -d" " -f2 | cut -c2-4)"

ffmpeg -y -i "$1" -ac 2 "$tmpaudio"
mp3gain "$tmpaudio"
ffmpeg -y -i "$1" -i "$tmpaudio" -c:v copy -c:a ac3 -sameq -map $videomap -map 1:0 "$tmpvideo" && \
  rm "$1" "$tmpaudio" && mv "$tmpvideo" "$1"

