#!/bin/bash

number() {
  grep -E [0-9]+$ "$1"
}

if [ $# -ne 1 ]; then 
	echo -e "\e[1mUsage\e[0m: vid2mp4 <inputvideo>"; 
	exit 3; 
fi

FILENAME="$1"

# Retira metadados do vídeo destino.
EXTRA_PARAMS="-map_metadata -1"

# Pega o nome do codec de vídeo.
VCODEC="$(ffprobe -v error -select_streams v:0 -show_entries stream=codec_name -of default=nw=1:nk=1 "$1")"

# Ajusta parâmetros de compressão para h264
if [ "$VCODEC" == "h264" ]; then
  VPARAMS="-c:v copy"
else
  VPARAMS="-c:v libx264 -crf 20"
fi

# Pega o nome do codec de audio.
ACODEC="$(ffprobe -v error -select_streams a:0 -show_entries stream=codec_name -of default=nw=1:nk=1 "$1")"

if [ "$ACODEC" == "ac3" ]; then
  APARAMS="-c:a copy"
elif [ ! -z "$ACODEC" ]; then
  # Pega o bitrate de audio.

  ABR="$(number "`ffprobe -v error -select_streams a:0 -show_entries stream=bit_rate -of default=nw=1:nk=1 "$1"`")"

  if [ ! -z "$ABR" ]; then
    ABR=$(($ABR / 1000))
    if [ $ABR -le 64 ]; then ABR=64; else
      if [ $ABR -lt 96 ]; then ABR=96; else
        if [ $ABR -lt 128 ]; then ABR=128; else
          if [ $ABR -lt 160 ]; then ABR=160; else
            ABR=192; 
          fi 
        fi 
      fi 
    fi
  else
    # ... mas, se não for, usa 128k.
    echo -e "\e[1mWarning\e[0m: Cannot find audio bitrate. Using 128 kbps!"
    ABR=128
  fi

  APARAMS="-c:a ac3 -b:a ${ABR}k -ac 2"
else
  # Não tem audio!
  APARAMS="-an"
fi

TMPFNAME="$(mktemp /tmp/tmp_XXXXXXXXXX.mp4)"
OFNAME="${FILENAME%.*}.mp4"

ffmpeg -hide_banner -y -i "$FILENAME" $VPARAMS $APARAMS $EXTRA_PARAMS $TMPFNAME && \
  rm "$FILENAME" && \
  mv "$TMPFNAME" "$OFNAME"
