#!/bin/bash

if [ $# -lt 1 ]
then
	echo -e "\e[1mUsage\e[0m: vid2mpg <inputvideo>"; 
	exit 3; 
fi

FILENAME="$1"
FTYPE="${1#*.}"
FTYPE="${FTYPE^^*}"
if [ "$FTYPE" == "MPG" ] || [ "$FTYPE" == "MPEG" ]; then
  echo -e "\e[1mError\e[0m: File '$1' is already a MPEG video."
  exit 1
fi

EXTRA_PARAMS="-map_metadata -1" # Retira metadados do vídeo destino.

VPARAMS="-crf 20"

TMPFNAME="$(mktemp /tmp/tmp_XXXXXXXXXX.mpg)"
OFNAME="${FILENAME%.*}.mpg"

ffmpeg -y -i "$FILENAME" $VPARAMS $EXTRA_PARAMS $TMPFNAME && mv $TMPFNAME "$OFNAME"

