#!/bin/bash

if [ $# -lt 1 ]
then
	echo -e "\e[1mUsage\e[0m: vid2webm <inputvideo>"; 
	exit 3; 
fi

FILENAME="$1"

EXTRA_PARAMS="-map_metadata -1" # Retira metadados do vídeo destino.

# Usa preset do x264 com maior poder de análise.
VPARAMS="-c:v libvpx -crf 13 -b:v 0 -c:a libovorbis -threads 2"

TMPFNAME="$(mktemp /tmp/tmp_XXXXXXXXXX.webm)"
OFNAME="${FILENAME%.*}.webm"

ffmpeg -y -i "$FILENAME" $VPARAMS $EXTRA_PARAMS $TMPFNAME && rm "$FILENAME" && mv $TMPFNAME "$OFNAME"

