#!/bin/bash

if [ $# -ne 1 ]
then
  echo -e "\e[1mUsage\e[0m: vidbr <filename>"
  exit 3
fi

FILENAME=$1

VBR="$(ffprobe -v error -select_streams v:0 -show_entries stream=bit_rate -of default=nw=1:nk=1 "$1")"
ABR="$(ffprobe -v error -select_streams a:0 -show_entries stream=bit_rate -of default=nw=1:nk=1 "$1")"

VIDBR=${VBR:-'?'}
AUDBR=${ABR:-'?'}

if [ "$VBR" != "?" ]; then
  VBR=$((VBR/1000));
fi

if [ "$ABR" != "?" ]; then
  ABR=$((ABR/1000))
fi

echo "\"$1\" (video: $VBR kb/s, audio: $ABR kb/s)"

