#!/bin/bash

if [ $# -ne 1 ]
then
  echo -e "\e[1mUsage\e[0m: vidtime <file>"
  exit 3
fi

VDUR="$(ffprobe -v error -select_streams v:0 -show_entries stream=duration -of default=nw=1:nk=1 "$1")"

echo "\"$1\" ($VDUR seconds)"
