#!/bin/bash

#
# Converte vídeo usando ffmpeg para o formato MP4 usando os codecs h264 e ac3.
# Script para nautilus, mas pode ser usado manualmente.
#

FFMPEG_OPTIONS="-c:v libx264 -sameq -c:a ac3 -b:a 192k -ac 2 -map_metadata -1"

# Parameters:
#   $1 = original video
#   $2 = new video
ffvideo () {
  local TOTAL_FRAMES=$(mediainfo '--Inform=Video;%FrameCount%' "$1")

  ffmpeg -y -i "$1" $FFMPEG_OPTIONS "$2" 2>&1 | \
      awk -vRS="\r" \
        '$1 ~ /^frame/ \
         { \
           gsub(/frame=/,""); \
           percent=int(($1 / '$TOTAL_FRAMES')*100); \
           print "#Converting '"'$1'"'.\\nTotal Frames: '$TOTAL_FRAMES'\\t\\tCurrent Frame:" $1 "\\n\\nPercent complete: " percent " %"; \
           print percent; \
           fflush(); \
         }' | \
      zenity --progress \
             --auto-kill \
             --auto-close \
             --title="Converting..." \
             --width=500 \
             --percentage=0
}

if [ $# -lt 1 ]; then
  zenity --error --text="No files selected"
  exit
fi


while [ ! -z "$1" ]; do
  if [ -f "$1" ]; then
    TMPFILE="$(mktemp $(dirname "$1")/tmp_XXXXXXXXX.mp4)"

    ffvideo "$1" "$TMPFILE"

    if [ $? -eq 0 ]; then
      rm "$1"
      mv "$TMPFILE" "${1%.*}.mp4"
    fi
  fi

  shift
done
