#!/bin/bash

[[ $# -ne 1 ]] && {
  echo "Usage: comic2pdf <comicbook-file>";
  exit 3;
}

PDF_NAME="$(echo "$1" | sed 's/^\(.*\)\.cb[zr]$/\1/').pdf"

ebook-convert "$1" "$PDF_NAME" --dont-grayscale && rm "$1"
