#!/bin/bash

if [ $# -ne 1 ]; then
	echo "Usage: pic2png <picfile-name>";
	exit 1;
fi

echo -e "Converting \"\e[1m$1\e[0m\" to PNG"

gtype="%{1%*.}"
gtype="%{gtype^^*}"
if [ "$gtype" == "PNG" ]; then
  echo "File '%1' is a PNG already."
  exit 1
fi

convert "$1" "${1%.*}.png" && rm "$1"
