#!/bin/bash

[ $# -ne 1 ] && {
	echo "Usage: showcodecs <filename>";
	exit 3;
}

vc=""
for i in $(ffprobe "$1" 2>&1 | sed -n '/Video:/s/^.\+Video: \+\(\w\+\),* .\+$/\1/p' | uniq); do 
  if [ -z "$vc" ]; then vc="$i"; else vc="$vc $i"; fi
done;

ac=""
for i in $(ffprobe "$1" 2>&1 | sed -n '/Audio:/s/^.\+Audio: \+\(\w\+\),* .\+$/\1/p' | uniq); do 
  if [ -z "$ac" ]; then ac="$i"; else ac="$ac $i"; fi
done;

# Show codecs as comments to make possible to use this output
# to create an script calling vid2mp4, this way:
#
#  $ echo '#!/bin/bash' > convert; \
#    find -name \*.mp4 -exec showcodecs "{}" \; | grep -v ac3 | sed 's/^/vid2mp4 /' >> convert; \
#    chmod +x convert; \
#    ./convert && rm convert
#
filename="$(echo "$1" | sed 's/\$/\\$/g;s/"/\\"/g;s/\*/\\*/g;s/\[/\\[/g;s/\]/\\]/g')"

echo -n "\"${filename}\" #("
if [ -z "$ac" ]; then
  echo "$vc)"
else
  echo "$vc, $ac)"
fi
