#!/bin/bash

# Criado por Kl0nEz.
#
# O script "ouve" uma frase dita no microfone, envia para o Google para transformá-la em string,
# pede ao Google Translator para traduzí-la para inglês e "fala" a frase traduzida.
# 
 
# Poderíamos testar com:
# [ "$(whereis ffmpeg | cut -d: -f2)" == "" ] { echo "can't find arecord"; exit; }

[ -x /usr/bin/wget ]    || ( echo "cant't find wget"; exit; )
[ -x /usr/bin/ffmpeg ]  || ( echo "can't find ffmpeg"; exit; )
[ -x /usr/bin/lynx ]    || ( echo "can't find lynx"; exit; )
[ -x /usr/bin/mplayer ] || ( echo "can't find mplayer"; exit )

FROM_LANG="pt"; FROM_LANG2="pt-br"
TO_LANG="en"

say() { 
  local IFS=+;
  mplayer -ao alsa -really-quiet -noconsolecontrols "http://translate.google.com/translate_tts?ie=UTF-8&tl=${TO_LANG}&q=$*" 2> /dev/null; 
}

TMP_FLAC="$(mktemp /tmp/tmp_XXXXXXXXXXXX.flac)"

trap "" INT

echo "Recording... Press Ctrl+C to Stop."

ffmpeg -f alsa -i hw:0 -ar 16000 -ac 1 -acodec flac "$TMP_FLAC" > /dev/null 2>&1

echo "Processing..."

wget -q -U "Mozilla/5.0" \
     --post-file "$TMP_FLAC" \
     --header "Content-Type: audio/x-flac; rate=16000" \
      -O - "http://www.google.com/speech-api/v1/recognize?lang=${FROM_LANG2}&client=chromium" | \
        cut -d\" -f12  > stt.txt

string=`cat stt.txt`

echo "You Said: $string"

en_string=`lynx -source "http://translate.google.com?tr=${FROM_LANG}&hl=${TO_LANG}&text=$string" | \
  awk 'gsub("<[^/]", "\n&")' | 
  grep '<span title' | 
  cut -d"<" -f2 | cut -d">" -f2`

say $en_string

#rm -f $TMP_FLAC

