#!/bin/bash

[[ $# -lt 1 ]] && { 
	echo "Usage: vid2mp4 <inputvideo> [film|animation]"; 
	exit 3; 
}

EXTRA_PARAMS="-map_metadata -1" # Retira metadados do vídeo destino.

# Usa preset do x264 com maior poder de análise.
VPARAMS="-c:v libx264 -qmin 1 -qmax 10"

if ffprobe "$1" 2>&1 | grep Audio: 2>&1 /dev/null; then
  ABR=$(ffmpeg -i "$1" 2>&1 | grep Audio: | sed 's/^.*, \([0-9]*\) kb\/s.*$/\1/');
  if [ $ABR -le 64 ]; then ABR=64; else
  if [ $ABR -le 96 ]; then ABR=96; else
  if [ $ABR -le 128 ]; then ABR=128; else
  if [ $ABR -le 160 ]; then ABR=160; else
  if [ $ABR -le 192 ]; then ABR=192; else
  if [ $ABR -le 256 ]; then ABR=256; else
    ABR=384;
  fi fi fi fi fi fi

  ABR=$ABR"k";
  APARAMS="-c:a ac3 -b:a $ABR -ac 2"
  unset ABR
else
  APARAMS="-an"
fi

TMPFNAME="$(mktemp /tmp/tmp_XXXXXXXXXX.mp4)"
OFNAME="${1%.*}.mp4"

ffmpeg -y -i "$1" $VPARAMS $APARAMS $EXTRA_PARAMS "$TMPFNAME" && \
  rm "$1" && \
  mv "$TMPFNAME" "$OFNAME"

unset VPARAMS
unset APARAMS
unset EXTRA_PARAMS
unset TMPFNAME
unset OFNAME

