#!/bin/bash

if [ $# -ne 1 ]
then
  echo -e "\e[1mUsage\e[0m: vidbr <filename>"
  exit 3
fi

FILENAME=$1

FILEBR="`ffprobe "$1" 2>&1 | sed -n 's/^.*Duration:.*bitrate: \([0-9]\+\) kb\/s.*$/\1/p'`"
VIDBR="`ffprobe "$1" 2>&1 | sed -n 's/^.*Video:.* \([0-9]\+\) kb\/s.*$/\1/p'`"
AUDBR="`ffprobe "$1" 2>&1 | sed -n 's/^.*Audio:.* \([0-9]\+\) kb\/s.*$/\1/p'`"

FILEBR=${FILEBR:-'?'}
VIDBR=${VIDBR:-'?'}
AUDBR=${AUDBR:-'?'}

echo "\"$1\" (total: $FILEBR kb/s, video: $VIDBR kb/s, audio: $AUDBR kb/s)"

